# vim: set expandtab:
debug: False # If True, enables debug output messages

#################################################
### Home Assistant Server Connection Settings ###
#################################################
home_assistant:
  # Hostname or IP address of the HomeAssistant server.
  host: hass.internal

  # True if a SSL connection to the HomeAssistant server should be used,
  # False for regular HTTP.
  ssl: False

  # Custom port to use to connect to use when connecting to the server,
  # Set to ~ if default port should be used instead.
  port: 8123

  # Legacy password to use to connect to the HomeAssistant server. Newer
  # versions of HomeAssistant have deprecated this in favour of long-lived
  # access tokens.
  api_password: ~

  # Long lived access token to use to connect to the HomeAssistant server. See
  # the Authentication section of the HomeAssistant documentation on how to
  # create of these for your server.
  api_token: ~

#################################################
###     StreamDeck Configuration Settings     ###
#################################################
streamdeck:
  # Brightness percentage of the backlight when in use. Should range from 0 to 100.
  brightness: 100

  # Timeout in seconds before the screen backlight is turned off automatically.
  # Set to ~ or 0 to keep backlight on indefinitely.
  screensaver: ~

defaults:
  label: '{name}'
  label_font: Assets/Fonts/Dosis-SemiBold.ttf
  label_size: 16
  value_font: Assets/Fonts/Dosis-Light.ttf
  value_size: 18

#################################################
###        Tile Configuration Settings        ###
#################################################
tiles:
  # Each tile should define how that tile should be rendered when the associated
  # HomeAssistant entity is in a given state. This allows screens to be defined
  # as a collection of tiles bound to different entities so that all entities of
  # the same type (e.g. all lights) are drawn in the same way.

  - type: "light"
    class: 'HassTile'
    states:
      - state: 'on'
        overlay: 'Assets/Images/icons8-light-on-72.png'
        action: 'turn_off'
      - state: ~
        overlay: 'Assets/Images/icons8-light-off-72.png'
        action: 'turn_on'

  - type: "fan"
    class: 'HassTile'
    states:
      - state: 'on'
        overlay: 'Assets/Images/icons8-fan-speed-72.png'
        action: 'turn_off'
      - state: ~
        overlay: 'Assets/Images/icons8-fan-speed-72.png'
        action: 'turn_on'
        overlay_mode: 'L'

  - type: "heat"
    class: 'HassTile'
    states:
      - state: 'on'
        overlay: 'Assets/Images/icons8-heating-72.png'
        action: 'turn_off'
      - state: ~
        overlay: 'Assets/Images/icons8-heating-72.png'
        action: 'turn_on'
        overlay_mode: 'L'

  - type: "switch"
    class: 'HassTile'
    states:
      - state: 'on'
        overlay: 'Assets/Images/icons8-switch-on-72.png'
        action: 'turn_off'
      - state: ~
        overlay: 'Assets/Images/icons8-switch-off-72.png'
        action: 'turn_on'

  - type: "media_power"
    class: 'HassTile'
    states:
      - state: ~
        overlay: 'Assets/Images/icons8-switch-on-72.png'
        action: 'turn_off'
      - state: 'off'
        overlay: 'Assets/Images/icons8-switch-off-72.png'
        action: 'turn_on'

  - type: "media_play_pause"
    class: 'HassTile'
    states:
      - state: 'playing'
        overlay: 'Assets/Images/icons8-pause-squared-72.png'
        action: 'media_player/media_pause'
      - state: 'paused'
        overlay: 'Assets/Images/icons8-start-72.png'
        action: 'media_player/media_play'
      - state: ~
        overlay: 'Assets/Images/icons8-start-72.png'
        overlay_mode: 'L'

  - type: "media_next"
    class: 'HassTile'
    states:
      - state: 'playing'
        overlay: 'Assets/Images/icons8-last-72.png'
        action: 'media_player/media_next_track'
      - state: ~
        overlay: 'Assets/Images/icons8-last-72.png'
        overlay_mode: 'L'

  - type: "media_previous"
    class: 'HassTile'
    states:
      - state: 'playing'
        overlay: 'Assets/Images/icons8-first-72.png'
        action: 'media_player/media_previous_track'
      - state: ~
        overlay: 'Assets/Images/icons8-first-72.png'
        overlay_mode: 'L'

  - type: "media_stop"
    class: 'HassTile'
    states:
      - state: 'playing'
        overlay: 'Assets/Images/icons8-stop-squared-72.png'
        action: 'media_player/media_stop'
      - state: ~
        overlay: 'Assets/Images/icons8-stop-squared-72.png'
        overlay_mode: 'L'

  - type: "media_mute"
    class: 'HassTile'
    states:
      - state: 'playing'
        overlay: 'Assets/Images/icons8-mute-72.png'
        action: 'media_player/volume_mute'
      - state: ~
        overlay: 'Assets/Images/icons8-mute-72.png'
        overlay_mode: 'L'

  - type: "media_volume_down"
    class: 'HassTile'
    states:
      - state: 'playing'
        overlay: 'Assets/Images/icons8-low-volume-72.png'
        action: 'media_player/volume_down'
      - state: ~
        overlay: 'Assets/Images/icons8-low-volume-72.png'
        overlay_mode: 'L'

  - type: "media_volume_up"
    class: 'HassTile'
    states:
      - state: 'playing'
        overlay: 'Assets/Images/icons8-voice-72.png'
        action: 'media_player/volume_up'
      - state: ~
        overlay: 'Assets/Images/icons8-voice-72.png'
        overlay_mode: 'L'

  - type: "climate_power"
    class: 'HassTile'
    states:
      - state: 'off'
        overlay: 'Assets/Images/icons8-air-conditioner-72.png'
        value: '{current_temperature}°C'
        action: 'climate/turn_on'
        overlay_mode: 'L'
      - state: ~
        overlay: 'Assets/Images/icons8-air-conditioner-72.png'
        value: '{current_temperature}°C'
        action: 'climate/turn_off'

  - type: "temperature"
    class: 'HassTile'
    states:
      - state: ~
        value: '{state}°C'
        overlay: 'Assets/Images/icons8-temperature-72.png'
        action: ~

  - type: "home"
    class: 'PageTile'
    states:
      - state: ~
        overlay: 'Assets/Images/icons8-home-72.png'

  - type: "bedroom"
    class: 'PageTile'
    states:
      - state: ~
        overlay: 'Assets/Images/icons8-bedroom-72.png'

  - type: "kitchen"
    class: 'PageTile'
    states:
      - state: ~
        overlay: 'Assets/Images/icons8-kitchen-room-72.png'

  - type: "office"
    class: 'PageTile'
    states:
      - state: ~
        overlay: 'Assets/Images/icons8-office-72.png'

templates:
  - name: "media_player"
    tiles:
      - position: [0, 0]
        type: "media_power"
        name: ""
      - position: [1, 0]
        type: "media_previous"
        name: ""
      - position: [2, 0]
        type: "media_play_pause"
        name: ""
      - position: [3, 0]
        type: "media_stop"
        name: ""
      - position: [4, 0]
        type: "media_next"
        name: ""
      - position: [5, 0]
        type: "media_mute"
        name: ""
      - position: [6, 0]
        type: "media_volume_down"
        name: ""
      - position: [7, 0]
        type: "media_volume_up"
        name: ""


#################################################
###    Screen Layout Configuration Settings   ###
#################################################
screens:
  # Each screen consists of one or more tiles of various types, bound to an
  # entity or page. The "home" page is mandatory, and is the one shown when the
  # script starts.

  - name: "home"
    tiles:
      - position: [1, 0]
        type: "kitchen"
        name: ""
        page: "downstairs"
      - position: [2, 0]
        type: "office"
        name: ""
        page: "study"
      - position: [3, 0]
        type: "bedroom"
        name: ""
        page: "bedroom"
  - name: "study"
    tiles:
      - position: [0, 0]
        type: "home"
        name: ""
        page: ~
      - position: [1, 0]
        type: "light"
        name: "Computer"
        entity_id: "light.computer"
      - position: [2, 0]
        type: "light"
        name: "Workbench"
        entity_id: "light.workbench"
      - position: [3, 0]
        type: "light"
        name: "Lamp"
        entity_id: "light.lamp"
      - position: [4, 0]
        type: "light"
        name: "Stairs"
        entity_id: "light.nanoleaf"
      - position: [5, 0]
        type: "light"
        name: "Room"
        entity_id: "switch.study_lights"
      - position: [0, 2]
        type: "temperature"
        name: "3D nozzle"
        entity_id: "sensor.octoprint_tool_0_temperature"
      - position: [1, 2]
        type: "temperature"
        name: "3D bed"
        entity_id: "sensor.octoprint_bed_temperature"
  - name: "downstairs"
    tiles:
      - position: [0, 0]
        type: "home"
        name: ""
        page: ~
      - position: [1, 0]
        type: "light"
        name: "Dining"
        entity_id: "light.dining"
      - position: [2, 0]
        type: "light"
        name: "Stove"
        entity_id: "light.kitchen_stove"
      - position: [3, 0]
        type: "light"
        name: "Sink"
        entity_id: "light.kitchen_middle"
      - position: [4, 0]
        type: "light"
        name: "Bench"
        entity_id: "light.kitchen_window"
      - position: [5, 0]
        type: "light"
        name: "TV"
        entity_id: "light.tv"
      - position: [6, 0]
        type: "light"
        name: "Couch"
        entity_id: "light.couch"
      - position: [7, 0]
        type: "light"
        name: "Party"
        entity_id: "light.party_lights"
      - position: [1, 1]
        type: "fan"
        name: "Toilet"
        entity_id: "switch.toilet_exhaust"
      - position: [2, 1]
        type: "light"
        name: "Toilet"
        entity_id: "switch.toilet_light"
      - position: [3, 1]
        type: "light"
        name: "Laundry"
        entity_id: "switch.laundry_downlight"
      - position: [4, 1]
        type: "heat"
        name: "Laundry"
        entity_id: "switch.laundry_heat_lamp"
      - position: [0, 2]
        template: "media_player"
        entity_id: "media_player.downstairs_av"
      - position: [0, 3]
        template: "media_player"
        entity_id: "media_player.projector_av"
  - name: "bedroom"
    tiles:
      - position: [0, 0]
        type: "home"
        name: ""
        page: ~
      - position: [2, 0]
        type: "climate_power"
        name: ""
        entity_id: "climate.bedroom"
      - position: [0, 2]
        template: "media_player"
        entity_id: "media_player.bedroom_av"

